networks:
  savvy-network:
    driver: bridge
    name: savvy-network

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - savvy-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: on-failure
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - savvy-network

  user-service:
    build:
      context: ../savvy-app-backend/user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ../savvy-app-backend/user-service:/app/src
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/user_service
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      KAFKA_BROKER: kafka:9093
    networks:
      - savvy-network

  transaction-service:
    build:
      context: ../savvy-app-backend/transaction-service
      dockerfile: Dockerfile
    container_name: transaction-service
    restart: on-failure
    ports:
      - "8081:8081"
    volumes:
      - ../savvy-app-backend/transaction-service:/app/src
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/transaction_service
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      KAFKA_BROKER: kafka:9093
    networks:
      - savvy-network

  budgeting-service:
    build:
      context: ../savvy-app-backend/budgeting-service
      dockerfile: Dockerfile
    container_name: budgeting-service
    restart: on-failure
    ports:
      - "8082:8082"
    volumes:
      - ../savvy-app-backend/budgeting-service:/app/src
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/budgeting_service
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      KAFKA_BROKER: kafka:9093
    networks:
      - savvy-network

  api-gateway:
    build: ../savvy-app-gateway
    container_name: api-gateway
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - user-service
      - transaction-service
      - budgeting-service
    networks:
      - savvy-network

volumes:
  postgres_user_data:
  postgres_transaction_data:
  postgres_budgeting_data:
