services:
  postgres-user:
    image: postgres:15
    container_name: postgres-user
    restart: on-failure
    secrets:
      - postgres_password
    environment:
      POSTGRES_USER: /run/secrets/database_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: user_service
    ports:
      - "5433:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  postgres-transaction:
    image: postgres:15
    container_name: postgres-transaction
    restart: on-failure
    secrets:
      - postgres_password
    environment: 
      POSTGRES_USER: /run/secrets/database_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: transaction_service
    ports:
      - "5434:5432"
    volumes:
      - postgres_transaction_data:/var/lib/postgresql/data

  postgres-budgeting:
    image: postgres:15
    container_name: postgres-budgeting
    restart: on-failure
    secrets: 
      - postgres_password
    environment:
      POSTGRES_USER: /run/secrets/database_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: budgeting_service
    ports:
      - "5435:5432"
    volumes:
      - postgres_budgeting_data:/var/lib/postgresql/data

  postgres-common:
    image: postgres:15
    container_name: postgres-common
    restart: on-failure
    secrets:
      - postgres_password
    environment:
      POSTGRES_USER: /run/secrets/database_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB: common_data
    ports:
      - "5436:5432"
    volumes:
      - postgres_common_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ../savvy-app-backend/user-service
    container_name: user-service
    restart: on-failure
    secrets:
      - postgres_password
    ports:
      - "8080:8080"
    volumes:
      - ../savvy-app-backend/user-service:/app
    depends_on:
      - postgres-user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/user-service
      SPRING_DATASOURCE_USERNAME: /run/secrets/database_user
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/postgres_password
      DATABASE_USER: "$(cat /run/secrets/database_user)"
      POSTGRES_PASSWORD: "$(cat /run/secrets/postgres_password)"
    
  transaction-service:
    build:
      context: ../savvy-app-backend/transaction-service
    container_name: transaction-service
    restart: on-failure
    secrets:
      - postgres_password
    ports:
      - "8081:8081"
    volumes:
      - ../savvy-app-backend/transaction-service:/app
    depends_on:
      - postgres-transaction
      - postgres-common
    environment:
      #Primary DB
      PRIMARY_DATASOURCE_URL: jdbc:postgresql://postgres-transaction:5432/transaction-service
      PRIMARY_DATASOURCE_USERNAME: /run/secrets/database_user

      #SharedD DB
      SHARED_DATASOURCE_URL: jdbc:postgresql://postgres-common:5432/common-data
      SHARED_DATASOURCE_USERNAME: /run/secrets/database_user

      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/postgres_password
      DATABASE_USER: "$(cat /run/secrets/database_user)"
      POSTGRES_PASSWORD: "$(cat /run/secrets/postgres_password)"
    
  budgeting-service:
    build:
      context: ../savvy-app-backend/budgeting-service
    container_name: budgeting-service
    restart: on-failure
    secrets:
      - postgres_password
    ports: 
      - "8082:8082"
    volumes:
      - ../savvy-app-backend/budgeting-service:/app
    depends_on:
      - postgres-budgeting
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-budgeting:5432/budgeting-service
      SPRING_DATASOURCE_USERNAME: /run/secrets/database_user
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/postgres_password
      DATABASE_USER: "$(cat /run/secrets/database_user)"
      POSTGRES_PASSWORD: "$(cat /run/secrets/postgres_password)"

  api-gateway:
    build: ../savvy-app-gateway
    container_name: api-gateway
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - user-service
      - transaction-service
      - budgeting-service

volumes:
  postgres_user_data:
  postgres_transaction_data:
  postgres_budgeting_data:
  postgres_common_data:

secrets:
  postgres_password:
    file: ../secrets/postgres_password
  database_user:
    file: ../secrets/database_user
  