global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:8080"]

  - job_name: "user-service-test"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service-test:8084"]

  - job_name: "transaction-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["transaction-service:8081"]

  - job_name: "transaction-service-test"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["transaction-service-test:8083"]

  - job_name: "budgeting-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["budgeting-service:8082"]
