apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: infra-transaction-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            # Primary Database
            - name: PRIMARY_DATASOURCE_URL
              value: jdbc:postgresql://postgres-transaction:5432/transaction-service
            - name: PRIMARY_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database_user

            # Shared Database
            - name: SHARED_DATASOURCE_URL
              value: jdbc:postgresql://postgres-common:5432/common-data
            - name: SHARED_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database_user

            # Secrets for Passwords
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres_password
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: postgres_password
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
