apiVersion: v1
kind: Service
metadata:
  name: budgeting-service
spec:
  selector:
    app: budgeting-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budgeting-service
  template:
    metadata:
      labels:
        app: budgeting-service
    spec:
      containers:
        - name: budgeting-service
          image: infra-budgeting-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://budgeting-db:5432/budgeting_service
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: KAFKA_BROKER
              value: kafka.kafka.svc.cluster.local:9092
