apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-https
data:
  default.conf: |
    upstream user-service {
        server user-service.default.svc.cluster.local:8080;
    }

    upstream transaction-service {
        server transaction-service.default.svc.cluster.local:8081;
    }

    upstream budgeting-service {
        server budgeting-service.default.svc.cluster.local:8082;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        location /api/users/ {
            limit_req zone=one burst=5;
            proxy_set_header Authorization $http_authorization;
            proxy_pass http://user-service;
        }

        location /api/payment_requests/ {
            limit_req zone=one burst=5;
            proxy_set_header Authorization $http_authorization;
            proxy_pass http://user-service;
        }

        location /api/transactions/ {
            limit_req zone=one burst=5;
            proxy_set_header Authorization $http_authorization;
            proxy_pass http://transaction-service;
        }

        location /api/budgeting/ {
            limit_req zone=one burst=5;
            proxy_set_header Authorization $http_authorization;
            proxy_pass http://budgeting-service;
        }

        error_page 500 502 503 504 /50x.html;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            return 301 https://$host$request_uri;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        limit_req_zone $binary_remote_addr zone=one:10m rate=1r/s;

        include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-https
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-https
  template:
    metadata:
      labels:
        app: nginx-https
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 443
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: certs-volume
              mountPath: /etc/nginx/certs
            - name: nginx-conf-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
        - name: certs-volume
          secret:
            secretName: nginx-tls
        - name: nginx-conf-volume
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-https
spec:
  type: NodePort
  selector:
    app: nginx-https
  ports:
    - port: 443
      targetPort: 443
      nodePort: 30443
