name: Budgeting Service CI

on: [push, pull_request]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: budgeting-service
      SERVICE_PATH: savvy-app-backend/budgeting-service

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle Wrapper
        run: chmod +x $SERVICE_PATH/gradlew

      - name: SonarCloud Analysis
        run: ./gradlew sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: ${{ env.SERVICE_PATH }}

      - name: Install Snyk CLI
        run: npm install -g snyk
      
      - name: Snyk Gradle Scan
        run: |
          snyk test --all-sub-projects || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GRADLE_HOME: ${{ env.SERVICE_PATH }}
        working-directory: ${{ env.SERVICE_PATH }}

      - name: Build JAR
        run: ./gradlew bootJar
        working-directory: ${{ env.SERVICE_PATH }}

      - name: Set lowercase image tag
        run: |
          OWNER_LC=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LC=$OWNER_LC" >> $GITHUB_ENV
          echo "IMAGE_TAG=ghcr.io/${OWNER_LC}/${{ env.SERVICE_NAME }}:${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t $IMAGE_TAG .
        working-directory: ${{ env.SERVICE_PATH }}

      - name: Scan Docker image with Snyk CLI
        run: |
          snyk container test ${{ env.IMAGE_TAG }} --severity-threshold=high || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Push Docker image
        run: docker push $IMAGE_TAG

      - name: Tag image as latest
        run: docker tag $IMAGE_TAG ghcr.io/${OWNER_LC}/${{ env.SERVICE_NAME }}:latest
      
      - name: Push latest tag
        run: docker push ghcr.io/${OWNER_LC}/${{ env.SERVICE_NAME }}:latest
