name: Transaction Service CI

on: [push, pull_request]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: transaction-service
      SERVICE_PATH: savvy-app-backend/transaction-service
      IMAGE_TAG: ghcr.io/${{ github.repository_owner }}/transaction-service:${{ github.sha }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build JAR with Gradle
        working-directory: savvy-app-backend/transaction-service
        run: ./gradlew build
      
      - name: Set lowercase image tag
        run: |
          OWNER_LC=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_TAG=ghcr.io/${OWNER_LC}/transaction-service:${GITHUB_SHA}" >> $GITHUB_ENV
      
      - name: Build Docker image
        run: docker build -t $IMAGE_TAG .
        working-directory: savvy-app-backend/transaction-service
      
      - name: Push Docker image
        run: docker push $IMAGE_TAG
